/* Gramatica.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. Gramatica.java */
package sintactico;
import jflexpackage.*;

public class Gramatica/*@bgen(jjtree)*/implements GramaticaTreeConstants, GramaticaConstants {/*@bgen(jjtree)*/
  protected JJTGramaticaState jjtree = new JJTGramaticaState();public static void main(String [] args) throws ParseException {
        Gramatica analizador = new Gramatica(System.in);
        SimpleNode root = analizador.program();
        //root.dump("");
    }

  final public SimpleNode program() throws ParseException {/*@bgen(jjtree) program */
  SimpleNode jjtn000 = new SimpleNode(JJTPROGRAM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(PROGRAM);
      lbrace();
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case INT:
        case FLOAT:
        case BOOL:{
          ;
          break;
          }
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        lista_decl();
      }
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LBRACE:
        case IF:
        case WHILE:
        case DO:
        case READ:
        case WRITE:
        case BREAK:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[1] = jj_gen;
          break label_2;
        }
        lista_sent();
      }
      rbrace();
      jj_consume_token(0);
jjtree.closeNodeScope(jjtn000, true);
  jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
    jjtree.clearNodeScope(jjtn000);
    jjtc000 = false;
  } else {
    jjtree.popNode();
  }
  if (jjte000 instanceof RuntimeException) {
    {if (true) throw (RuntimeException)jjte000;}
  }
  if (jjte000 instanceof ParseException) {
    {if (true) throw (ParseException)jjte000;}
  }
  {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
    jjtree.closeNodeScope(jjtn000, true);
  }
    }
    throw new Error("Missing return statement in function");
  }

  final public void lista_decl() throws ParseException {/*@bgen(jjtree) lista_decl */
  SimpleNode jjtn000 = new SimpleNode(JJTLISTA_DECL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      decl();
    } catch (Throwable jjte000) {
if (jjtc000) {
                         jjtree.clearNodeScope(jjtn000);
                         jjtc000 = false;
                       } else {
                         jjtree.popNode();
                       }
                       if (jjte000 instanceof RuntimeException) {
                         {if (true) throw (RuntimeException)jjte000;}
                       }
                       if (jjte000 instanceof ParseException) {
                         {if (true) throw (ParseException)jjte000;}
                       }
                       {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
                         jjtree.closeNodeScope(jjtn000, true);
                       }
    }
  }

  final public void decl() throws ParseException {/*@bgen(jjtree) decl */
    SimpleNode jjtn000 = new SimpleNode(JJTDECL);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);String type = "";
    //CMTC1
    jjtn000.value = "Declaracion";
    try {
      type = tipo();
      lista_id(type);
      semicolon();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public String tipo() throws ParseException {/*@bgen(jjtree) tipo */
    SimpleNode jjtn000 = new SimpleNode(JJTTIPO);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);String type = "";
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:{
        type = intToken();
jjtree.closeNodeScope(jjtn000, true);
                      jjtc000 = false;
{if ("" != null) return type;}
        break;
        }
      case FLOAT:{
        type = floatToken();
jjtree.closeNodeScope(jjtn000, true);
                         jjtc000 = false;
{if ("" != null) return type;}
        break;
        }
      case BOOL:{
        type = boolToken();
jjtree.closeNodeScope(jjtn000, true);
                        jjtc000 = false;
{if ("" != null) return type;}
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public void lista_id(String type) throws ParseException {/*@bgen(jjtree) lista_id */
  SimpleNode jjtn000 = new SimpleNode(JJTLISTA_ID);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      idDecl(type);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[3] = jj_gen;
          break label_3;
        }
        comma();
        idDecl(type);
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void lista_sent() throws ParseException {/*@bgen(jjtree) lista_sent */
  SimpleNode jjtn000 = new SimpleNode(JJTLISTA_SENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      sent();
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LBRACE:
        case IF:
        case WHILE:
        case DO:
        case READ:
        case WRITE:
        case BREAK:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          break label_4;
        }
        sent();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
                          jjtree.clearNodeScope(jjtn000);
                          jjtc000 = false;
                        } else {
                          jjtree.popNode();
                        }
                        if (jjte000 instanceof RuntimeException) {
                          {if (true) throw (RuntimeException)jjte000;}
                        }
                        if (jjte000 instanceof ParseException) {
                          {if (true) throw (ParseException)jjte000;}
                        }
                        {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
                          jjtree.closeNodeScope(jjtn000, true);
                        }
    }
  }

  final public void sent() throws ParseException {/*@bgen(jjtree) sent */
  SimpleNode jjtn000 = new SimpleNode(JJTSENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:{
        sent_if();
        break;
        }
      case WHILE:{
        sent_while();
        break;
        }
      case DO:{
        sent_do();
        break;
        }
      case READ:{
        sent_read();
        break;
        }
      case WRITE:{
        sent_write();
        break;
        }
      case LBRACE:{
        bloque();
        break;
        }
      case ID:{
        sent_assign();
        break;
        }
      case BREAK:{
        breakToken();
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
                   jjtree.clearNodeScope(jjtn000);
                   jjtc000 = false;
                 } else {
                   jjtree.popNode();
                 }
                 if (jjte000 instanceof RuntimeException) {
                   {if (true) throw (RuntimeException)jjte000;}
                 }
                 if (jjte000 instanceof ParseException) {
                   {if (true) throw (ParseException)jjte000;}
                 }
                 {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
                   jjtree.closeNodeScope(jjtn000, true);
                 }
    }
  }

  final public void sent_if() throws ParseException {/*@bgen(jjtree) sent_if */
    SimpleNode jjtn000 = new SimpleNode(JJTSENT_IF);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);SymbolNode tempVar;
    try {
      ifToken();
      lparen();
      tempVar = exp_bool();
SymTable.AddTemporalIndex(tempVar);
      rparen();
      then();
      bloque();
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ELSE:{
          ;
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          break label_5;
        }
        elseToken();
        bloque();
      }
      fi();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void sent_while() throws ParseException {/*@bgen(jjtree) sent_while */
    SimpleNode jjtn000 = new SimpleNode(JJTSENT_WHILE);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);SymbolNode tempVar;
    try {
      whileToken();
      lparen();
      tempVar = exp_bool();
SymTable.AddTemporalIndex(tempVar);
      rparen();
      bloque();
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value= "SentWhile";
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void sent_do() throws ParseException {/*@bgen(jjtree) sent_do */
    SimpleNode jjtn000 = new SimpleNode(JJTSENT_DO);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);SymbolNode tempVar;
    try {
      doToken();
      bloque();
      until();
      lparen();
      tempVar = exp_bool();
SymTable.AddTemporalIndex(tempVar);
      rparen();
      semicolon();
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void sent_read() throws ParseException {/*@bgen(jjtree) sent_read */
  SimpleNode jjtn000 = new SimpleNode(JJTSENT_READ);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      read();
      id();
      semicolon();
    } catch (Throwable jjte000) {
if (jjtc000) {
                         jjtree.clearNodeScope(jjtn000);
                         jjtc000 = false;
                       } else {
                         jjtree.popNode();
                       }
                       if (jjte000 instanceof RuntimeException) {
                         {if (true) throw (RuntimeException)jjte000;}
                       }
                       if (jjte000 instanceof ParseException) {
                         {if (true) throw (ParseException)jjte000;}
                       }
                       {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
                         jjtree.closeNodeScope(jjtn000, true);
                       }
    }
  }

  final public void sent_write() throws ParseException {/*@bgen(jjtree) sent_write */
  SimpleNode jjtn000 = new SimpleNode(JJTSENT_WRITE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      write();
      id();
      semicolon();
    } catch (Throwable jjte000) {
if (jjtc000) {
                         jjtree.clearNodeScope(jjtn000);
                         jjtc000 = false;
                       } else {
                         jjtree.popNode();
                       }
                       if (jjte000 instanceof RuntimeException) {
                         {if (true) throw (RuntimeException)jjte000;}
                       }
                       if (jjte000 instanceof ParseException) {
                         {if (true) throw (ParseException)jjte000;}
                       }
                       {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
                         jjtree.closeNodeScope(jjtn000, true);
                       }
    }
  }

  final public void bloque() throws ParseException {/*@bgen(jjtree) bloque */
  SimpleNode jjtn000 = new SimpleNode(JJTBLOQUE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      lbrace();
      lista_sent();
      rbrace();
jjtree.closeNodeScope(jjtn000, true);
                                                   jjtc000 = false;
jjtn000.value="Bloque";
    } catch (Throwable jjte000) {
if (jjtc000) {
                      jjtree.clearNodeScope(jjtn000);
                      jjtc000 = false;
                    } else {
                      jjtree.popNode();
                    }
                    if (jjte000 instanceof RuntimeException) {
                      {if (true) throw (RuntimeException)jjte000;}
                    }
                    if (jjte000 instanceof ParseException) {
                      {if (true) throw (ParseException)jjte000;}
                    }
                    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
                      jjtree.closeNodeScope(jjtn000, true);
                    }
    }
  }

  final public void sent_assign() throws ParseException {/*@bgen(jjtree) sent_assign */
    SimpleNode jjtn000 = new SimpleNode(JJTSENT_ASSIGN);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);String identifier="";
    SymbolNode tempVar = null;
    jjtn000.value = "Asignacion";
    try {
      identifier = idAssign();
      assign();
      tempVar = exp_bool();
      semicolon();
jjtree.closeNodeScope(jjtn000, true);
                                                                     jjtc000 = false;
if(SymTable.Contains(identifier)){
            SymbolNode id = SymTable.GetIndex(identifier);
            if((id.type == tempVar.type) || (id.type =="float" && (tempVar.type == "float" || tempVar.type=="int"))){
                SymTable.UpdateIndex(identifier, tempVar);
                if(id.type =="float" && tempVar.type=="int"){
                    IDE.errores += "Warning: P\u00e9rdida de precisi\u00f3n. \u005cn";
                }
            }else {//error, tipos de datos diferentes
                IDE.errores += "Error: El tipo de dato no es compatible. \u005cn";
            }
        }else{IDE.errores += "Error: Var no declarada \u005cn";} //error, variable no declarada

    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public SymbolNode exp_bool() throws ParseException {/*@bgen(jjtree) exp_bool */
    SimpleNode jjtn000 = new SimpleNode(JJTEXP_BOOL);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);SymbolNode acum1;
    SymbolNode acum2;
    SymbolNode acum3 = new SymbolNode("",null);
    try {
      acum1 = comb();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case OR:{
          ;
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          break label_6;
        }
        or();
        acum2 = comb();
acum3.value = ((Boolean) acum1.value).booleanValue() || ((Boolean) acum2.value).booleanValue() ? true : false;
                    acum3.type="bool";
                    {if ("" != null) return acum3;}
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return acum1;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public SymbolNode comb() throws ParseException {/*@bgen(jjtree) comb */
    SimpleNode jjtn000 = new SimpleNode(JJTCOMB);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);SymbolNode acum1;
    SymbolNode acum2;
    SymbolNode acum3 = new SymbolNode("",null);
    try {
      acum1 = igualdad();
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case AND:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_7;
        }
        and();
        acum2 = igualdad();
acum3.value = ((Boolean) acum1.value).booleanValue() && ((Boolean) acum2.value).booleanValue() ? true : false;
                      acum3.type="bool";
                      {if ("" != null) return acum3;}
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return acum1;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public SymbolNode igualdad() throws ParseException {/*@bgen(jjtree) igualdad */
    SimpleNode jjtn000 = new SimpleNode(JJTIGUALDAD);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);SymbolNode acum1;
    SymbolNode acum2;
    SymbolNode acum3 = new SymbolNode("",null);
    String op = "";
    try {
      acum1 = rel();
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case EQ:
        case NEQ:{
          ;
          break;
          }
        default:
          jj_la1[9] = jj_gen;
          break label_8;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case EQ:{
          op = eq();
          break;
          }
        case NEQ:{
          op = neq();
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        acum2 = rel();
double numericValue1 = 0.0;
                    double numericValue2 = 0.0;

                    if (acum1.value instanceof Integer) {
                        numericValue1 = (int) acum1.value;
                    } else if (acum1.value instanceof Double) {
                        numericValue1 = (double) acum1.value;
                    }else numericValue1 = ((Boolean) acum1.value).booleanValue() == true ? 1 : 0;

                    if (acum2.value instanceof Integer) {
                        numericValue2 = (int) acum2.value;
                    } else if (acum2.value instanceof Double) {
                        numericValue2 = (double) acum2.value;
                    }else numericValue2 = ((Boolean) acum2.value).booleanValue() == true ? 1 : 0;

                    switch(op) {
                        case "==":
                            acum3.value = numericValue1 == numericValue2;
                            break;
                        case "!=":
                            acum3.value = numericValue1 != numericValue2;
                            break;
                    }
                    acum3.type = "bool";
                    {if ("" != null) return acum3;}
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return acum1;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public SymbolNode rel() throws ParseException {/*@bgen(jjtree) rel */
    SimpleNode jjtn000 = new SimpleNode(JJTREL);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);SymbolNode acum1;
    SymbolNode acum2;
    SymbolNode acum3 = new SymbolNode("", null);
    String op = "";
    try {
      acum1 = expr();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LT:
      case LTE:
      case GT:
      case GTE:{
        op = op_rel();
        acum2 = expr();
double numericValue1 = 0.0;
                    double numericValue2 = 0.0;

                    if (acum1.value instanceof Integer) {
                        numericValue1 = (int) acum1.value;
                    } else if (acum1.value instanceof Double) {
                        numericValue1 = (double) acum1.value;
                    }

                    if (acum2.value instanceof Integer) {
                        numericValue2 = (int) acum2.value;
                    } else if (acum2.value instanceof Double) {
                        numericValue2 = (double) acum2.value;
                    }

                    switch(op) {
                        case "<":
                            acum3.value = numericValue1 < numericValue2;
                            break;
                        case "<=":
                            acum3.value = numericValue1 <= numericValue2;
                            break;
                        case ">":
                            acum3.value = numericValue1 > numericValue2;
                            break;
                        case ">=":
                            acum3.value = numericValue1 >= numericValue2;
                            break;
                    }
                    acum3.type="bool";
                    {if ("" != null) return acum3;}
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return acum1;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public String op_rel() throws ParseException {/*@bgen(jjtree) op_rel */
    SimpleNode jjtn000 = new SimpleNode(JJTOP_REL);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);String op ="";
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LT:{
        op = lt();
jjtree.closeNodeScope(jjtn000, true);
           jjtc000 = false;
{if ("" != null) return op;}
        break;
        }
      case LTE:{
        op = lte();
jjtree.closeNodeScope(jjtn000, true);
                                  jjtc000 = false;
{if ("" != null) return op;}
        break;
        }
      case GT:{
        op = gt();
jjtree.closeNodeScope(jjtn000, true);
                                                        jjtc000 = false;
{if ("" != null) return op;}
        break;
        }
      case GTE:{
        op = gte();
jjtree.closeNodeScope(jjtn000, true);
                                                                               jjtc000 = false;
{if ("" != null) return op;}
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public SymbolNode expr() throws ParseException {/*@bgen(jjtree) expr */
    SimpleNode jjtn000 = new SimpleNode(JJTEXPR);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);SymbolNode acum1 = null;
    SymbolNode acum2 = null;
    try {
      acum1 = term();
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PLUS:
        case MINUS:{
          ;
          break;
          }
        default:
          jj_la1[13] = jj_gen;
          break label_9;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PLUS:{
          plus();
          acum2 = term();
acum1.value = (acum1.type == "float" ? ((Number) acum1.value).doubleValue() : ((Number) acum1.value).intValue())
                        + (acum2.type == "float" ? ((Number) acum2.value).doubleValue() : ((Number) acum2.value).intValue());

                        if(acum1.type == "float" || acum2.type == "float") acum1.type = "float";
                        else acum1.type = "int";
          break;
          }
        case MINUS:{
          minus();
          acum2 = term();
acum1.value = (acum1.type == "float" ? ((Number) acum1.value).doubleValue() : ((Number) acum1.value).intValue())
                        - (acum2.type == "float" ? ((Number) acum2.value).doubleValue() : ((Number) acum2.value).intValue());

                        if(acum1.type == "float" || acum2.type == "float") acum1.type = "float";
                        else acum1.type = "int";
          break;
          }
        default:
          jj_la1[14] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return acum1;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public SymbolNode term() throws ParseException {/*@bgen(jjtree) term */
    SimpleNode jjtn000 = new SimpleNode(JJTTERM);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);SymbolNode acum1 = null;
    SymbolNode acum2 = null;
    try {
      acum1 = unario();
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ASTERISK:
        case SLASH:{
          ;
          break;
          }
        default:
          jj_la1[15] = jj_gen;
          break label_10;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ASTERISK:{
          asterisk();
          acum2 = unario();
acum1.value = (acum1.type == "float" ? ((Number) acum1.value).doubleValue() : ((Number) acum1.value).intValue())
                        * (acum2.type == "float" ? ((Number) acum2.value).doubleValue() : ((Number) acum2.value).intValue());

                        if(acum1.type == "float" || acum2.type == "float") acum1.type = "float";
                        else acum1.type = "int";
          break;
          }
        case SLASH:{
          slash();
          acum2 = unario();
acum1.value = (acum1.type == "float" ? ((Number) acum1.value).doubleValue() : ((Number) acum1.value).intValue())
                        / (acum2.type == "float" ? ((Number) acum2.value).doubleValue() : ((Number) acum2.value).intValue());

                        if(acum1.type == "float" || acum2.type == "float") acum1.type = "float";
                        else acum1.type = "int";
          break;
          }
        default:
          jj_la1[16] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return acum1;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public SymbolNode unario() throws ParseException {/*@bgen(jjtree) unario */
    SimpleNode jjtn000 = new SimpleNode(JJTUNARIO);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);SymbolNode acum1 = null;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NOT:{
        not();
        unario();
        break;
        }
      case MINUS:{
        minus();
        unario();
        break;
        }
      case LPAREN:
      case TRUE:
      case FALSE:
      case ID:
      case INTEGER:
      case REAL:{
        acum1 = factor();
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return acum1;}
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public SymbolNode factor() throws ParseException {/*@bgen(jjtree) factor */
    SimpleNode jjtn000 = new SimpleNode(JJTFACTOR);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);SymbolNode acum1 = null;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:{
        lparen();
        exp_bool();
        rparen();
jjtree.closeNodeScope(jjtn000, true);
                                   jjtc000 = false;
{if ("" != null) return acum1;}
        break;
        }
      case ID:{
        acum1 = id();
jjtree.closeNodeScope(jjtn000, true);
                                                               jjtc000 = false;
{if ("" != null) return acum1;}
        break;
        }
      case INTEGER:{
        acum1 = integer();
jjtree.closeNodeScope(jjtn000, true);
                                                                                                jjtc000 = false;
{if ("" != null) return acum1;}
        break;
        }
      case REAL:{
        acum1 = real();
jjtree.closeNodeScope(jjtn000, true);
                                                                                                                               jjtc000 = false;
{if ("" != null) return acum1;}
        break;
        }
      case TRUE:{
        acum1 = trueToken();
jjtree.closeNodeScope(jjtn000, true);
                                                                                                                                                                   jjtc000 = false;
{if ("" != null) return acum1;}
        break;
        }
      case FALSE:{
        acum1 = falseToken();
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return acum1;}
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public void lbrace() throws ParseException {/*@bgen(jjtree) lbrace */
  SimpleNode jjtn000 = new SimpleNode(JJTLBRACE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LBRACE);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;

    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void rbrace() throws ParseException {/*@bgen(jjtree) rbrace */
  SimpleNode jjtn000 = new SimpleNode(JJTRBRACE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(RBRACE);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;

    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void lbracket() throws ParseException {/*@bgen(jjtree) lbracket */
  SimpleNode jjtn000 = new SimpleNode(JJTLBRACKET);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LBRACKET);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;

    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void rbracket() throws ParseException {/*@bgen(jjtree) rbracket */
  SimpleNode jjtn000 = new SimpleNode(JJTRBRACKET);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(RBRACKET);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;

    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void lparen() throws ParseException {/*@bgen(jjtree) lparen */
  SimpleNode jjtn000 = new SimpleNode(JJTLPAREN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LPAREN);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;

    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void rparen() throws ParseException {/*@bgen(jjtree) rparen */
  SimpleNode jjtn000 = new SimpleNode(JJTRPAREN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(RPAREN);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;

    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void semicolon() throws ParseException {/*@bgen(jjtree) semicolon */
  SimpleNode jjtn000 = new SimpleNode(JJTSEMICOLON);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(SEMICOLON);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value=";";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void comma() throws ParseException {/*@bgen(jjtree) comma */
  SimpleNode jjtn000 = new SimpleNode(JJTCOMMA);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(COMMA);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value=",";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void assign() throws ParseException {/*@bgen(jjtree) assign */
  SimpleNode jjtn000 = new SimpleNode(JJTASSIGN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ASSIGN);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="=";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void or() throws ParseException {/*@bgen(jjtree) or */
  SimpleNode jjtn000 = new SimpleNode(JJTOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(OR);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="or";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void and() throws ParseException {/*@bgen(jjtree) and */
  SimpleNode jjtn000 = new SimpleNode(JJTAND);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(AND);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="and";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public String eq() throws ParseException {/*@bgen(jjtree) eq */
  SimpleNode jjtn000 = new SimpleNode(JJTEQ);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(EQ);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="==";
        {if ("" != null) return token.image;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public String neq() throws ParseException {/*@bgen(jjtree) neq */
  SimpleNode jjtn000 = new SimpleNode(JJTNEQ);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(NEQ);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="!=";
        {if ("" != null) return token.image;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public String lt() throws ParseException {/*@bgen(jjtree) lt */
  SimpleNode jjtn000 = new SimpleNode(JJTLT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LT);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="<";
        {if ("" != null) return token.image;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public String lte() throws ParseException {/*@bgen(jjtree) lte */
  SimpleNode jjtn000 = new SimpleNode(JJTLTE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LTE);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="<=";
        {if ("" != null) return token.image;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public String gt() throws ParseException {/*@bgen(jjtree) gt */
  SimpleNode jjtn000 = new SimpleNode(JJTGT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(GT);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value=">";
        {if ("" != null) return token.image;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public String gte() throws ParseException {/*@bgen(jjtree) gte */
  SimpleNode jjtn000 = new SimpleNode(JJTGTE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(GTE);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value=">=";
        {if ("" != null) return token.image;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public void plus() throws ParseException {/*@bgen(jjtree) plus */
  SimpleNode jjtn000 = new SimpleNode(JJTPLUS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(PLUS);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="+";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void minus() throws ParseException {/*@bgen(jjtree) minus */
  SimpleNode jjtn000 = new SimpleNode(JJTMINUS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(MINUS);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="-";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void asterisk() throws ParseException {/*@bgen(jjtree) asterisk */
  SimpleNode jjtn000 = new SimpleNode(JJTASTERISK);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ASTERISK);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="*";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void slash() throws ParseException {/*@bgen(jjtree) slash */
  SimpleNode jjtn000 = new SimpleNode(JJTSLASH);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(SLASH);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="/";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void not() throws ParseException {/*@bgen(jjtree) not */
  SimpleNode jjtn000 = new SimpleNode(JJTNOT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(NOT);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="not";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void ifToken() throws ParseException {/*@bgen(jjtree) ifToken */
  SimpleNode jjtn000 = new SimpleNode(JJTIFTOKEN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(IF);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="if";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void fi() throws ParseException {/*@bgen(jjtree) fi */
  SimpleNode jjtn000 = new SimpleNode(JJTFI);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FI);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="fi";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void elseToken() throws ParseException {/*@bgen(jjtree) elseToken */
  SimpleNode jjtn000 = new SimpleNode(JJTELSETOKEN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ELSE);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="else";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void whileToken() throws ParseException {/*@bgen(jjtree) whileToken */
  SimpleNode jjtn000 = new SimpleNode(JJTWHILETOKEN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(WHILE);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="while";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void doToken() throws ParseException {/*@bgen(jjtree) doToken */
  SimpleNode jjtn000 = new SimpleNode(JJTDOTOKEN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(DO);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="do";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void until() throws ParseException {/*@bgen(jjtree) until */
  SimpleNode jjtn000 = new SimpleNode(JJTUNTIL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(UNTIL);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="until";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void read() throws ParseException {/*@bgen(jjtree) read */
  SimpleNode jjtn000 = new SimpleNode(JJTREAD);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(READ);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="read";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void write() throws ParseException {/*@bgen(jjtree) write */
  SimpleNode jjtn000 = new SimpleNode(JJTWRITE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(WRITE);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="write";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public void breakToken() throws ParseException {/*@bgen(jjtree) breakToken */
  SimpleNode jjtn000 = new SimpleNode(JJTBREAKTOKEN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(BREAK);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="break";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public String intToken() throws ParseException {/*@bgen(jjtree) intToken */
  SimpleNode jjtn000 = new SimpleNode(JJTINTTOKEN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(INT);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="int";
        {if ("" != null) return token.image;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public String floatToken() throws ParseException {/*@bgen(jjtree) floatToken */
  SimpleNode jjtn000 = new SimpleNode(JJTFLOATTOKEN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FLOAT);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="float";
        {if ("" != null) return token.image;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public String boolToken() throws ParseException {/*@bgen(jjtree) boolToken */
  SimpleNode jjtn000 = new SimpleNode(JJTBOOLTOKEN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(BOOL);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="bool";
        {if ("" != null) return token.image;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public SymbolNode trueToken() throws ParseException {/*@bgen(jjtree) trueToken */
  SimpleNode jjtn000 = new SimpleNode(JJTTRUETOKEN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(TRUE);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="true";
        {if ("" != null) return new SymbolNode("bool", true);}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public SymbolNode falseToken() throws ParseException {/*@bgen(jjtree) falseToken */
  SimpleNode jjtn000 = new SimpleNode(JJTFALSETOKEN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FALSE);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="false";
        {if ("" != null) return new SymbolNode("bool", false);}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public void then() throws ParseException {/*@bgen(jjtree) then */
  SimpleNode jjtn000 = new SimpleNode(JJTTHEN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(THEN);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="then";
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public SymbolNode id() throws ParseException {/*@bgen(jjtree) id */
  SimpleNode jjtn000 = new SimpleNode(JJTID);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ID);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="" + token.image;
        {if ("" != null) return SymTable.GetIndex(token.image);}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public void idDecl(String type) throws ParseException {/*@bgen(jjtree) idDecl */
  SimpleNode jjtn000 = new SimpleNode(JJTIDDECL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ID);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="" + token.image;
        SymTable.AddIndex(token.image, type);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  final public String idAssign() throws ParseException {/*@bgen(jjtree) idAssign */
  SimpleNode jjtn000 = new SimpleNode(JJTIDASSIGN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ID);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="" + token.image;
        {if ("" != null) return token.image;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public SymbolNode integer() throws ParseException {/*@bgen(jjtree) integer */
  SimpleNode jjtn000 = new SimpleNode(JJTINTEGER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(INTEGER);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="" + token.image;
        {if ("" != null) return new SymbolNode("int", Integer.parseInt(token.image));}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public SymbolNode real() throws ParseException {/*@bgen(jjtree) real */
  SimpleNode jjtn000 = new SimpleNode(JJTREAL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(REAL);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.value="" + token.image;
        {if ("" != null) return new SymbolNode("float", Double.parseDouble(token.image));}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public GramaticaTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[19];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x90000040,0x0,0x2000,0x90000040,0x90000040,0x40000000,0x8000,0x10000,0x60000,0x60000,0x780000,0x780000,0x1800000,0x1800000,0x6000000,0x6000000,0x9000400,0x400,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0xe0,0x81d,0xe0,0x0,0x81d,0x81d,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x3b00,0x3b00,};
   }

  /** Constructor with InputStream. */
  public Gramatica(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Gramatica(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new GramaticaTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Gramatica(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new GramaticaTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Gramatica(GramaticaTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(GramaticaTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[50];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 19; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 50; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
