/* Generated By:JavaCC: Do not edit this line. GramaticaTreeConstants.java Version 6.0_1 */
package sintactico;

public interface GramaticaTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTLISTA_DECL = 1;
  public int JJTDECL = 2;
  public int JJTTIPO = 3;
  public int JJTLISTA_ID = 4;
  public int JJTLISTA_SENT = 5;
  public int JJTSENT = 6;
  public int JJTSENT_IF = 7;
  public int JJTSENT_WHILE = 8;
  public int JJTSENT_DO = 9;
  public int JJTSENT_READ = 10;
  public int JJTSENT_WRITE = 11;
  public int JJTBLOQUE = 12;
  public int JJTSENT_ASSIGN = 13;
  public int JJTEXP_BOOL = 14;
  public int JJTCOMB = 15;
  public int JJTIGUALDAD = 16;
  public int JJTREL = 17;
  public int JJTOP_REL = 18;
  public int JJTEXPR = 19;
  public int JJTTERM = 20;
  public int JJTUNARIO = 21;
  public int JJTFACTOR = 22;


  public String[] jjtNodeName = {
    "program",
    "lista_decl",
    "decl",
    "tipo",
    "lista_id",
    "lista_sent",
    "sent",
    "sent_if",
    "sent_while",
    "sent_do",
    "sent_read",
    "sent_write",
    "bloque",
    "sent_assign",
    "exp_bool",
    "comb",
    "igualdad",
    "rel",
    "op_rel",
    "expr",
    "term",
    "unario",
    "factor",
  };
}
/* JavaCC - OriginalChecksum=05e6b8d2024f208acbde609f82c0596a (do not edit this line) */
